Repository KNU-HAEDAL/1day1baek, pull requests merged in 2024-05, with the labels that each got.

#18 깃헙 로그입 버튼 구현
  front/src/components/header/MainNavigation.tsx
  front/src/pages/login/LoginPage.tsx
  front/src/pages/login/components/GithubButton.tsx
Labels: ✨ Feature, 🧑‍💻 FE, 💄 Design

#26 로그인 완료 후, 리다이렉션 Url을 `/login/code`로 변경
  back/src/main/kotlin/knu/dong/onedayonebaek/oauth/OAuth2SuccessHandler.kt
Labels: 🐛 BugFix, 🧑‍💻 BE

#28 샌드박스 설정 추가
  back/run_sandbox.sh
  back/src/main/resources/application-sandbox.yml
  back/src/main/resources/secrets.yml.sample
Labels: 🐛 BugFix, 🚀 Deploy, 🧑‍💻 BE

#30 깃헙으로부터 받는 유저의 이메일 필드 삭제 및 name의 널 처리
  back/src/main/kotlin/knu/dong/onedayonebaek/oauth/service/CustomOAuth2UserService.kt
Labels: 🐛 BugFix, 🧑‍💻 BE

#34 백엔드 Github Actions CD 파이프라인 구축
  .github/workflows/deploy.yml
Labels: 🚀 Deploy, 🧑‍💻 BE

#42 commits -> problems 도메인 이름 변경
  back/src/main/kotlin/knu/dong/onedayonebaek/controller/ProblemController.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/domain/Problem.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/dto/CommitInfo.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/dto/ProblemDto.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/repository/CommitRepository.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/repository/ProblemRepository.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/service/ProblemService.kt
Labels: ♻️ Refactoring, 🧑‍💻 BE

#43 그룹원들의 해결한 문제 조회 API 구현
  back/src/main/kotlin/knu/dong/onedayonebaek/controller/GroupController.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/dto/DateUnit.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/dto/ProblemsOfUser.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/repository/ContainGroupRepository.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/repository/ProblemRepository.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/service/GroupService.kt
Labels: ✨ Feature, 🧑‍💻 BE

#47 그룹원 내보내기 기능 구현
  back/src/main/kotlin/knu/dong/onedayonebaek/common/exception/ForbiddenException.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/common/exception/GlobalExceptionHandler.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/common/exception/NotFoundException.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/group/controller/GroupController.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/group/service/GroupService.kt
Labels: ✨ Feature, 🧑‍💻 BE

#57 깃헙 로그인 API 연결
  front/.eslintrc.cjs
  front/.gitignore
  front/package.json
  front/pnpm-lock.yaml
  front/src/Router.tsx
  front/src/components/alarm/ToastProvider.tsx
  front/src/components/header/MainNavigation.tsx
  front/src/constants/.keep
  front/src/constants/URI.ts
  front/src/main.tsx
  front/src/pages/login/LoginRedirectPage.tsx
  front/src/pages/login/components/GithubButton.tsx
  front/src/stores/useTokenStore.ts
  front/src/styles/GlobalStyles.ts
  front/tsconfig.json
Labels: ✨ Feature, 📦 Environment, 👽 API, 🧑‍💻 FE

#59 `GET /groups/:groupId/fine` 구현
  back/src/main/kotlin/knu/dong/onedayonebaek/containgroup/service/ContainGroupService.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/fine/controller/FineController.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/fine/dto/GetFinesDto.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/fine/service/FineService.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/group/controller/GroupController.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/group/domain/Group.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/group/dto/CreateOrUpdateGroupRequest.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/group/dto/GroupDetailDto.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/group/service/GroupService.kt
Labels: ✨ Feature, 🧑‍💻 BE

#60 벌금 계산에 하루에 풀어야하는 개수를 반영
  back/src/main/kotlin/knu/dong/onedayonebaek/fine/service/FineService.kt
Labels: ✨ Feature, 🧑‍💻 BE

#61 그룹 둘러보기 기능 구현
  front/src/Router.tsx
  front/src/components/header/MainNavigation.tsx
  front/src/components/header/test/MainNavigation.test.tsx
  front/src/hooks/queries/Http.ts
  front/src/hooks/queries/search/getGroupsQuery.ts
  front/src/interfaces/GroupInterface.ts
  front/src/mocks/handler/Handler.ts
  front/src/mocks/handler/search/SearchHandler.ts
  front/src/pages/mypage/MyPage.tsx
  front/src/pages/search/SearchPage.tsx
  front/src/pages/search/components/SearchResult.tsx
  front/src/services/.keep
  front/src/services/API_JWT.ts
  front/src/services/search/getGroups.tsx
Labels: ✨ Feature, 👽 API, 🧑‍💻 FE, 💄 Design

#63 requestparam이 비었을 때 nullpointerexception을 뱉는 버그 해결
  back/src/main/kotlin/knu/dong/onedayonebaek/problem/controller/ProblemController.kt
Labels: 🐛 BugFix, 🧑‍💻 BE

#64 `GET /problems/count` 반환 타입 변경
  back/src/main/kotlin/knu/dong/onedayonebaek/problem/controller/ProblemController.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/problem/dto/GetProblemCountOfDayResponse.kt
Labels: ✨ Feature, 🧑‍💻 BE

#66 피드 페이지 API 연결하기
  front/src/hooks/queries/feed/getProblems.ts
  front/src/hooks/queries/feed/getUserCommitQuery.ts
  front/src/hooks/queries/feed/getUserDataQuery.ts
  front/src/interfaces/ProblemInterface.ts
  front/src/pages/feed/FeedPage.tsx
  front/src/pages/feed/components/ProblemList.tsx
  front/src/pages/feed/components/Profile.tsx
  front/src/pages/search/SearchPage.tsx
  front/src/services/feed/getProblems.ts
  front/src/services/feed/getUserCommit.ts
  front/src/services/feed/getUserData.ts
  front/src/services/search/getGroups.ts
  front/src/styles/Layout.ts
Labels: ✨ Feature, 👽 API, 🧑‍💻 FE

#72 피드 페이지 및 다른 페이지 버그 해결
  front/src/hooks/queries/Http.ts
  front/src/hooks/queries/feed/getProblemMonth.ts
  front/src/hooks/queries/feed/getProblems.ts
  front/src/hooks/queries/feed/getUserCommitQuery.ts
  front/src/hooks/queries/feed/getUserDataQuery.ts
  front/src/hooks/queries/group/getMyGroupQuery.ts
  front/src/hooks/queries/search/getGroupsQuery.ts
  front/src/interfaces/GroupInterface.ts
  front/src/pages/feed/FeedPage.tsx
  front/src/pages/group/components/GroupLists.tsx
  front/src/pages/search/components/SearchResult.tsx
  front/src/services/feed/getProblemMonth.ts
Labels: 🐛 BugFix, 👽 API, 🧑‍💻 FE

#74 휴일 조회시 정렬 추가
  back/src/main/kotlin/knu/dong/onedayonebaek/fine/service/FineService.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/holiday/repository/HolidayRepository.kt
  back/src/main/kotlin/knu/dong/onedayonebaek/holiday/service/HolidayService.kt
Labels: ✨ Feature, 🧑‍💻 BE

#77 UserDto에 id추가
  back/src/main/kotlin/knu/dong/onedayonebaek/user/dto/UserDto.kt
Labels: ✨ Feature, 🧑‍💻 BE

#79 멤버 추방 기능 구현
  front/src/hooks/queries/group/deleteKickMemQuery.ts
  front/src/pages/group/components/AdminTeamProfile.tsx
  front/src/services/group/deleteKickMem.ts
Labels: 🐛 BugFix, ✨ Feature, 👽 API, 🧑‍💻 FE, 💄 Design

#81 프론트엔드 리드미 작성
  front/README.md
  front/src/pages/group/components/HolidayDeleteModal.tsx
Labels: 📝 Docs, 🧑‍💻 FE
